"""
__author__ = "Patrick Doyle"
__license__ = "The Unlicense"
__email__ = "me@pcdoyle.com"

Rosalind Bioinformatics:
    Complementing a Strand of DNA
    http://rosalind.info/problems/revc/

    Need to reverse the string, then swap all the complementing characters of that string.
    A -> T, T -> A, C -> G, G -> C
        Example Input: AAAACCCGGT
        Example Output: ACCGGGTTTT
"""
def reverseDNA(dnaString):
    '''
    Function reverses the DNA string then swaps the complementing characters.
    '''
    # Reverse the string:
    reversedDNA = dnaString[::-1]
    # Swap letters for lowercase ones, then make them uppercase:
    return reversedDNA.replace('A','t').replace('T','a').replace('C','g').replace('G','c').upper()

if __name__ == "__main__":
    # Start the program with the DNA string to swap to an RNA string.
    print(reverseDNA('AGGGGACGCCTGGAGGGGGCTCGTTCTACCACATAGAACGTACGTTTGCCTTATTTGTGAGAGTCCCGATAGGTGGCAGGAGTGTACAACACGTGGAGGGGGCCTTACTATAATATGGTTTCGCGGCATACCATCGCATAACGCATAATAGGCGTGCTCACACCAAGTGTTTGCACTGCTCATTCCTCATGGTTACATTCTTAGGCCGTGCTGTCATGGTACCTACAGCAATAAGACTGGGTTCCTAGGACTGTAGAACCTCTCAATGCAGCAATCATGCCAGGTTATCACCGGATCGAATCATCACTAAACCAGTGACCCAGACAGAACGACTCCACGAGCGACAGGCTATCTCTAAATACTCAAGAGAACTCCTATAACCATGCAGCAATGATATTGGTGATTATGTTAGGGCACCTCGTTGACCTCCTCAGACATTGCAAATGACAAACTGTTCGCTGAGCGTAATGTTTCGACAATCCTCCCAGCAACGGTACAAGTAGGTCCGACATATAATTGGCCGCCCTAATTATAATATGCGCGTCTGTTCCTGCATAAGCTCCTTTCAATAATAGGGTGACCGCGGGTAAAGATCGCCCGTTATCTGCAGCGATACTGTCCGACCGAGACCACAACAGTTGTACAGGAGCTCCCCACCGCGACCACTGTTTACCAAGATAACCACCGCGCGTAATCTACGTCCTCCCACTTGCTCAGGAGCCTTGTATGGGTGAACCGCTCTAGGACTCAGCCTCCCCACAATGGCGGCTGCGGACAATACCAGCATTAAGGACTGGACCCCAAGGCAGACTAGGCCTCCT'))